##### libraries
library(flextable)
library(ggplot2)
library(kableExtra)
library(tidyverse)
library(tidymodels)
library(tidyr)
library(purrr)
library(rstan)
library(rstanarm)
library(stats)
library(DescTools)
library(stats)
library(psych)
library(vcd)
library(expss)
library(rmarkdown)
library(Amelia)
library(finalfit)
library(jtools)
library(ggstance)
library(huxtable)
library(sjlabelled)
library(sjmisc)
library(sjPlot)
library(moderndive)
library(broom)
library(pcaPP)
library(haven)
library(gdata)
library(car)
library(forcats)
library(MASS)
library(leaps)
library(robustfa)
library(nnet)
library(brant)
library(ordinal)
library(effects)
library(rockchalk)
library(performance)
library(RColorBrewer)
library(vcd)
library(pander)
library(foreign)
library(glmnet)
library(randomForest)
library(ranger)
library(recipes)
library(caret)
library(rms)

#######################################################################################################

# ESS Data by countries
ESS_Nor <- read.spss(file = "/Users/flo/Documents/GitHub/FOSSOS_Project/ESS9NO.sav", to.data.frame = T)
ESS_Sve <- read.spss(file = "/Users/flo/Documents/GitHub/FOSSOS_Project/ESS9SE.sav", to.data.frame = T)
ESS_Fin <- read.spss(file = "/Users/flo/Documents/GitHub/FOSSOS_Project/ESS9FI.sav", to.data.frame = T)

### END?

